[package]
name = "bsky-rss-bot"
authors = ["Blooym"]
repository = "https://github.com/Blooym/bsky-tss-bot"
description = "A simple RSS feed subscriber -> Bluesky post bot."
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
reqwest = { version = "0.12.9" }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio"] }
log = "0.4.22"
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "env", "string"] }
dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
chrono = "0.4.38"
feed-rs = "2.1.1"
bsky-sdk = "0.1.12"
image = "0.25.5"
scraper = "0.21.0"
futures = "0.3.31"
dirs = "5.0.1"

[profile.release]
lto = true
codegen-units = 1
